server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /items {
        proxy_pass http://itemsapi-backend-service:8000/items;
        proxy_connect_timeout 5s;        
        proxy_read_timeout 10s;
    }

    error_page 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}