apiVersion: v1
kind: Service
metadata:
  name: itemsapi-backend-service
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: itemsapi-backend
  type: NodePort
  ports:
    - protocol: TCP
      port: {{.Values.backend.servicePort}}
      targetPort: 8000
      nodePort: {{.Values.backend.nodePort}}
